---

directories:
  ut_dir: .
  object_dir: objects
  source_dir: ../src
  mock_dir: mocks
  lib_dir: /usr/lib

ninja_variables:
  coverage_flag: --coverage
  color_flag: -fcolor-diagnostics
  compiler: clang++-11
  compiler_flags: "${color_flag} -c -g -Wall"
  linker: clang++-11
  linker_flags: "${coverage_flag} ${color_flag} -g -L ${lib_dir} -lgtest -lpthread -lgmock"

include_directories:
- ${mock_dir}
- ${source_dir}
- ${source_dir}/configs
- ${source_dir}/lcd/240x320
- ${ut_dir}/../submodules/etl/include
- /usr/src/googletest/googletest/include
- /usr/src/googletest/googlemock/include
