---

output_directory: output
target: output/midi-grid.elf
additional_outputs:
- output/midi-grid.hex
- output/midi-grid.bin
- output/midi-grid.map
- output/midi-grid.dfu

include_directories:
- submodules/cmsis_device_f4/Include
- submodules/cmsis_core/Include
- submodules/stm32f4xx_hal_driver/Inc
- submodules/stm32f4xx_hal_driver/Inc/Legacy
- middlewares/ST/STM32_USB_Device_Library/Core/Inc
- middlewares/USBMIDI/Inc
- src
- src/configs
- src/lcd/240x320
- submodules/etl/include
- submodules/freertos-addons/c++/Source/include
- submodules/FreeRTOS-Kernel/include
- submodules/FreeRTOS-Kernel/portable/GCC/ARM_CM4F/
  # using c and c++ libraries from arm-none-eabi-gcc atm
- /opt/gcc-arm-none-eabi-9/arm-none-eabi/include/c++/9.3.1/
- /opt/gcc-arm-none-eabi-9/arm-none-eabi/include/c++/9.3.1/arm-none-eabi

c_source_files:
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_adc.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_adc_ex.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_cortex.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_dma.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_dma_ex.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_flash.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_flash_ex.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_flash_ramfunc.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_gpio.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_pcd.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_pcd_ex.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_pwr.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_pwr_ex.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_rcc.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_rcc_ex.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_spi.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_tim.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_tim_ex.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_hal_uart.c
- submodules/stm32f4xx_hal_driver/Src/stm32f4xx_ll_usb.c
- middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
- middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
- middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
- middlewares/USBMIDI/Src/usbd_midi.c
- src/usb/usbd_conf.c
- src/usb/usbd_desc.c
- src/usb/usb_device.c
- src/system/stm32f4xx_it.c
- src/system/system_stm32f4xx.c
- submodules/FreeRTOS-Kernel/croutine.c
- submodules/FreeRTOS-Kernel/event_groups.c
- submodules/FreeRTOS-Kernel/list.c
- submodules/FreeRTOS-Kernel/queue.c
- submodules/FreeRTOS-Kernel/stream_buffer.c
- submodules/FreeRTOS-Kernel/tasks.c
- submodules/FreeRTOS-Kernel/timers.c
- submodules/FreeRTOS-Kernel/portable/GCC/ARM_CM4F/port.c
- submodules/FreeRTOS-Kernel/portable/MemMang/heap_1.c

cxx_source_files:
- src/application/Application.cpp
- src/application/grid_test/GridTest.cpp
- src/application/internal_menu/InternalMenu.cpp
- src/application/launchpad/Launchpad.cpp
- src/application/launchpad/LcdGui.cpp
- src/application/snake/Snake.cpp
- src/application/startup/Startup.cpp
- src/hardware/grid/GridDriver.cpp
- src/hardware/lcd/BacklightDriver.cpp
- src/hardware/lcd/Spi.cpp
- src/additional_buttons/AdditionalButtons.cpp
- src/grid/ButtonInput.cpp
- src/grid/FlashingLeds.cpp
- src/grid/Grid.cpp
- src/grid/GridContainer.cpp
- src/grid/LedOutput.cpp
- src/grid/PulsingLeds.cpp
- src/lcd/Lcd.cpp
- src/lcd/PriorityManager.cpp
- src/lcd/240x320/lcd/LcdContainer.cpp
- src/lcd/240x320/lcd/Ili9341.cpp
- src/lcd/240x320/lcd/Pixel.cpp
- src/lcd/backlight/Backlight.cpp
- src/lcd/font/nokia_8p.cpp
- src/lcd/font/monoton_80p.cpp
- src/lcd/font/rubik_16p.cpp
- src/lcd/font/rubik_24p.cpp
- src/lcd/font/sarpanch_79p.cpp
- src/lcd/image/Image.cpp
- src/lcd/images/circle_23x23.cpp
- src/lcd/images/circle_empty_23x23.cpp
- src/lcd/images/down_arrow_9x23.cpp
- src/lcd/images/midi_23x23.cpp
- src/lcd/images/triangle_21x23.cpp
- src/lcd/images/up_arrow_9x23.cpp
- src/lcd/images/usb_41x23.cpp
- src/lcd/images/usb_240x107.cpp
- src/lcd/shapes/Shapes.cpp
- src/lcd/text/Font.cpp
- src/lcd/text/Format.cpp
- src/lcd/text/Text.cpp
- src/syslog/Log.cpp
- src/syslog/LogContainer.cpp
- src/syslog/LogThread.cpp
- src/syslog/Storage.cpp
- src/rotary_controls/RotaryControls.cpp
- src/testing/Testing.cpp
- src/usb/UsbMidi.cpp
- src/main.cpp
- src/system/GlobalInterrupts.cpp
- src/system/System.cpp
- src/types/Color.cpp
- src/utilities/atoi.cpp
- submodules/freertos-addons/c++/Source/cqueue.cpp
- submodules/freertos-addons/c++/Source/csemaphore.cpp
- submodules/freertos-addons/c++/Source/cthread.cpp
- submodules/freertos-addons/c++/Source/cmutex.cpp

asm_source_files:
- submodules/cmsis_device_f4/Source/Templates/gcc/startup_stm32f413xx.s

linker_script: linker_script.ld
c_compiler: clang-11
cxx_compiler: clang++-11
asm_compiler: clang-11
linker: arm-none-eabi-g++
object_copy_utility: llvm-objcopy-11
object_information_utility: llvm-objdump-11
output_size_report_utility: llvm-size-11
dfu_conversion_utility: submodules/dfuse-tool/dfu-convert

arch_flags:
- -mcpu=cortex-m4
- -DUSE_HAL_DRIVER
- -DSTM32F413xx
- -mthumb
- -mfloat-abi=hard
- -mfpu=fpv4-sp-d16
- -mlittle-endian
- -fshort-enums
- --sysroot=/opt/gcc-arm-none-eabi-9/arm-none-eabi

c_flags:
- --target=arm-none-eabi
- -O1
- -ggdb3
- -ffunction-sections
- -fdata-sections
- -fdiagnostics-color=always

cxx_flags:
- -fno-rtti
- -fno-strict-aliasing
- -std=c++11
- -DCPP_FREERTOS_NO_EXCEPTIONS
- -DCPP_FREERTOS_NO_CPP_STRINGS

linker_flags:
- -Wl,--gc-sections
- -Wl,--warn-once
- -fdiagnostics-color=always
- -specs=nano.specs
- -specs=nosys.specs
