---

output_directory: output
target: output/midi-grid.elf
additional_outputs:
- output/midi-grid.hex
- output/midi-grid.bin
- output/midi-grid.map
- output/midi-grid.dfu

include_directories:
- drivers/CMSIS/Device/ST/STM32F4xx/Include
- drivers/CMSIS/Include
- drivers/STM32F4xx_HAL_Driver/Inc
- drivers/STM32F4xx_HAL_Driver/Inc/Legacy
- middlewares/ST/STM32_USB_Device_Library/Core/Inc
- middlewares/USBMIDI/Inc
- src
- src/configs
- src/lcd/84x48_mono
- submodules/etl/include
- submodules/freertos-addons/c++/Source/include
- submodules/FreeRTOS-Kernel/include
- submodules/FreeRTOS-Kernel/portable/GCC/ARM_CM4F/
  # using c and c++ libraries from arm-none-eabi-gcc atm
- /opt/gcc-arm-none-eabi-9-2019-q4-major/arm-none-eabi/include/c++/9.2.1/
- /opt/gcc-arm-none-eabi-9-2019-q4-major/arm-none-eabi/include/c++/9.2.1/arm-none-eabi

c_source_files:
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
- drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
- middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
- middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
- middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
- middlewares/USBMIDI/Src/usbd_midi.c
- src/usb/usbd_conf.c
- src/usb/usbd_desc.c
- src/usb/usb_device.c
- src/system/stm32f4xx_it.c
- src/system/system_stm32f4xx.c
- submodules/FreeRTOS-Kernel/croutine.c
- submodules/FreeRTOS-Kernel/event_groups.c
- submodules/FreeRTOS-Kernel/list.c
- submodules/FreeRTOS-Kernel/queue.c
- submodules/FreeRTOS-Kernel/stream_buffer.c
- submodules/FreeRTOS-Kernel/tasks.c
- submodules/FreeRTOS-Kernel/timers.c
- submodules/FreeRTOS-Kernel/portable/GCC/ARM_CM4F/port.c
- submodules/FreeRTOS-Kernel/portable/MemMang/heap_1.c

cxx_source_files:
- src/application/Application.cpp
- src/application/grid_test/GridTest.cpp
- src/application/internal_menu/InternalMenu.cpp
- src/application/launchpad/Launchpad.cpp
- src/application/launchpad/LcdGui.cpp
- src/application/snake/Snake.cpp
- src/application/startup/Startup.cpp
- src/hardware/grid/GridDriver.cpp
- src/hardware/lcd/BacklightDriver.cpp
- src/hardware/lcd/Spi.cpp
- src/additional_buttons/AdditionalButtons.cpp
- src/grid/ButtonInput.cpp
- src/grid/FlashingLeds.cpp
- src/grid/Grid.cpp
- src/grid/GridContainer.cpp
- src/grid/LedOutput.cpp
- src/grid/PulsingLeds.cpp
- src/lcd/backlight/Backlight.cpp
- src/lcd/Lcd.cpp
- src/lcd/84x48_mono/LcdContainer.cpp
- src/lcd/84x48_mono/Pcd8544.cpp
- src/log/Log.cpp
- src/log/LogContainer.cpp
- src/log/LogThread.cpp
- src/rotary_controls/RotaryControls.cpp
- src/testing/Testing.cpp
- src/usb/UsbMidi.cpp
- src/main.cpp
- src/system/GlobalInterrupts.cpp
- src/system/System.cpp
- src/types/Color.cpp
- submodules/freertos-addons/c++/Source/cqueue.cpp
- submodules/freertos-addons/c++/Source/csemaphore.cpp
- submodules/freertos-addons/c++/Source/cthread.cpp
- submodules/freertos-addons/c++/Source/cmutex.cpp

asm_source_files:
- startup/startup_stm32f411xe.S

linker_script: STM32F411RCTx_FLASH.ld
c_compiler: clang-9
cxx_compiler: clang++-9
asm_compiler: clang-9
linker: arm-none-eabi-g++
object_copy_utility: llvm-objcopy-9
object_information_utility: llvm-objdump-9
output_size_report_utility: llvm-size-9
dfu_conversion_utility: submodules/dfuse-tool/dfu-convert

arch_flags:
- -mcpu=cortex-m4
- -DUSE_HAL_DRIVER
- -DSTM32F411xE
- -mthumb
- -mfloat-abi=hard
- -mfpu=fpv4-sp-d16
- -fshort-enums
- --sysroot=/opt/gcc-arm-none-eabi-9-2019-q4-major/arm-none-eabi

c_flags:
- --target=arm-none-eabi
- -O0
- -ggdb3
- -ffunction-sections
- -fdata-sections
- -fdiagnostics-color=always

cxx_flags:
- -fno-rtti
- -fno-strict-aliasing
- -std=c++11
- -DCPP_FREERTOS_NO_EXCEPTIONS
- -DCPP_FREERTOS_NO_CPP_STRINGS

linker_flags:
- -Wl,--gc-sections
- -Wl,--warn-once
- -fdiagnostics-color=always
- -specs=nano.specs
- -specs=nosys.specs
